spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

jwt:
  secret: ${JWT_SECRET}

adapter:
  micro-plazoleta:
    url: ${PLAZOLETA_SERVICE_URL}

feign:
  client:
    config:
      micro-plazoleta:
        connectTimeout: 5000
        readTimeout: 5000
